# 🧮 Numpy
The first important library you **MUST** use whenever it comes to matrix/vector operations.
- Machine learning and deep learning techniques will assume matrix and vector input and will apply matrix/vector operations
- Whetner it's a vector (1D), matrix (2D) or even tensor (ND), Numpy calls it `ndarray`

Numpy provides ways to create high-performance multidimensional array objects, with operations over them, that make them very computationally efficient. 

Efficient?

Since it's written in C, NumPy also allows for **Parallelization** (and this HIGHLY depends on the code you write). 
- Python has what's known as GIL which is a mutex (or a lock) that allows only one thread to hold the control of the Python interpreter (this simplified the language implementation).
- However, such lock can be released by C extensions (Numpy is multi-threaded).

## How to use numpy
First you need to have the package installed on your python package manager (ANACONDA) using the command `conda install numpy`.

Then you import the package modules to your work script using:

`import numpy as np`

**GOOD PRACTICE** the `as np` in the last command is not mandatory, it is called an alias (or nickname) for the package so you can use `np` instead of `numpy`. A common practice is to use `np` to refer to `numpy`, and we will use `pd` for pandas and `plt` for `matplotlib` as you will see later in the file 

In [1]:
%pip install numpy
import numpy as np

Note: you may need to restart the kernel to use updated packages.


Check the documentation [here](https://numpy.org/doc/stable/reference/routines.html).

#### Arrays in NumPy
- Arrays in NumPy are like Matrices but can have any number of dimensions. 

- 1D arrays are called `vectors`, and nD arrays are high dimentional matrices, for example 2D. 

- **VERY IMPORTANT** For 2D matrices, the shape is (`row ,column`), and vectors in the matrices in NumPy are **Horizontal** not vertical like we learn in linear algebra.

There are multiple easy ways to create array objects from numpy.

## 1. Creating Arrays

From lists

In [7]:
## create array from values
np_arr = np.array([1, 2, 3, 4]) 

## print it (Python's perspective):
print(np_arr, "is of type", type(np_arr))

## use array_name.shape to get array shape
print("Its shape is", np_arr.shape)  

## use array_name.dtyoe to get type of array elements
print("Its data type", np_arr.dtype)

[1 2 3 4] is of type <class 'numpy.ndarray'>
Its shape is (4,)
Its data type int64


**IMPORTANT** Unlike lists in Python, NumPy arrays should have the same data type fro **ALL** its elements

In [6]:
## create 2D array using lists of lists syntax
two_dim_array = np.array([ [1, 2, 3], 
                           [4, 5, 6], 
                           [7, 8, 9]]) 

## print it
print(two_dim_array)   ## observe how the vectors above are Horizontal not vertical

## get its shape
print("Its shape is", two_dim_array.shape)  

## get its data type
print("Its data type", two_dim_array.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Its shape is (3, 3)
Its data type int64


In [9]:
# Create a 3D NumPy array with shape (2, 3, 4)
# This represents a 2x3 grid, each containing 4 elements
arr_3d = np.array([
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
    [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]
])

print(arr_3d.T)
print("Shape:", arr_3d.shape)

# Access
print(arr_3d[1, 2, 3])      # equivalent to indexing the input list with [1][2][3]

[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]
Shape: (2, 3, 4)
24
24


Creating arrays from values

In [5]:
## create an empty array of size 3*2
arr = np.empty((3,2)) 
print(arr) ## uninitialized

## create identity matrix of size 5*5 
identity = np.eye(5)
print(identity)

## create array full of 1s  of size 3*4
all_ones = np.ones((3, 4))  
print(all_ones)

## create array full of zeros of size 2*2
all_zeros = np.zeros((2,2))
print(all_zeros)

[[-0.00000000e+000 -0.00000000e+000]
 [-1.48219694e-323 -0.00000000e+000]
 [-9.88131292e-324  4.17201514e-309]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


#### Comprehensive Summary:

Their syntax `function_name(param0, param1[, param2, param3, ...])`
- function_name: This is the name of the function you're calling.
- `param0, param1`: These are a required parameters. You must provide a value for param1 when calling the function.
- `param2, param3, ...`: These are optional parameters. You can choose to provide values for any number of optional parameters, separated by commas.


#### From shape or value

| Function                                 | Description                                                                                                 |
|------------------------------------------|-------------------------------------------------------------------------------------------------------------|
| `empty(shape[, dtype, order, like])`    | Return a new array of given shape and type, without initializing entries.                                   |
| `empty_like(prototype[, dtype, order, subok, ...])` | Return a new array with the same shape and type as a given array.                                           |
| `eye(N[, M, k, dtype, order, like])`    | Return a 2-D array with ones on the diagonal and zeros elsewhere.                                            |
| `identity(n[, dtype, like])`            | Return the identity array.                                                                                  |
| `ones(shape[, dtype, order, like])`     | Return a new array of given shape and type, filled with ones.                                                |
| `ones_like(a[, dtype, order, subok, shape])` | Return an array of ones with the same shape and type as a given array.                                       |
| `zeros(shape[, dtype, order, like])`    | Return a new array of given shape and type, filled with zeros.                                               |
| `zeros_like(a[, dtype, order, subok, shape])` | Return an array of zeros with the same shape and type as a given array.                                      |
| `full(shape, fill_value[, dtype, order, like])` | Return a new array of given shape and type, filled with `fill_value`.                                        |
| `full_like(a, fill_value[, dtype, order, ...])` | Return a full array with the same shape and type as a given array.                                           |

`dtype` is by default `numpy.float64`, `order` is for memory layout (row 'C' or column major 'F'), `like` is extremely rarely used, `subok` extremely rarely used or doesn't exist.

#### From existing data

| Function                                 | Description                                                                                                 |
|------------------------------------------|-------------------------------------------------------------------------------------------------------------|
| `array(object[, dtype, copy, order, subok, ...])` | Create an array.                                                                                            |
| `asarray(a[, dtype, order, like])`      | Convert the input to an array (creates a copy only if needed).                                                                              |
| `ascontiguousarray(a[, dtype, like])`   | Return a contiguous array (ndim >= 1) in memory (C order).                                                   |
| `copy(a[, order, subok])`                | Return an array copy of the given object.                                                                   |


#### Numerical ranges

| Function                                 | Description                                                                                                 |
|------------------------------------------|-------------------------------------------------------------------------------------------------------------|
| `arange([start,] stop[, step,][, dtype, like])` | Return evenly spaced values within a given interval.                                                         |
| `linspace(start, stop[, num, endpoint, ...])` | Return evenly spaced numbers over a specified interval.                                                     |
| `logspace(start, stop[, num, endpoint, base, ...])` | Return numbers spaced evenly on a log scale.                                                                |
| `meshgrid(*xi[, copy, sparse, indexing])` | Return a list of coordinate matrices from coordinate vectors.                                                |

In [2]:
# Using np.arange()
arr1 = np.arange(0, 10, 2)  # start at 0, stop before 10, step by 2

# Using np.linspace() with appropriate number of elements
arr2 = np.linspace(0, 8, 5)  # start at 0, end at 8, with 5 elements (step size: (8-0)/(5-1) = 2)

print(arr1)
print(arr2)
# Checking if the arrays are equal
print(arr1 == arr2)                 # its done element-wise
print((arr1 == arr2).all())         # .all() and .any() are builtin Python functions that operare over Python collections

[0 2 4 6 8]
[0. 2. 4. 6. 8.]
[ True  True  True  True  True]
True



#### Building Matrices (2D Arrays)

| Function                                 | Description                                                                                                 |
|------------------------------------------|-------------------------------------------------------------------------------------------------------------|
| `diag(v[, k])`                           | Extract a diagonal or construct a diagonal array.                                                            |
| `diagflat(v[, k])`                       | Create a two-dimensional array with the flattened input as a diagonal.                                       |
| `tri(N[, M, k, dtype, like])`            | An array with ones at and below the given diagonal and zeros elsewhere.                                      |
| `tril(m[, k])`                           | Lower triangle of an array.                                                                                 |
| `triu(m[, k])`                           | Upper triangle of an array.         |
                                                                        
`k` specifies the diagonal if needed (default is as defined by mathematics)


## 2. Array Operations

NumPy allows many built-in matrix operations that are very useful

### Basic operations

| Function            | Description                                      |
|---------------------|--------------------------------------------------|
| copyto(dst, src)   | Copies values from one array to another, broadcasting as necessary. |
| shape(a)            | Return the shape of an array.                    |

### Changing array shape

| Function                | Description                                            |
|-------------------------|--------------------------------------------------------|
| reshape(a, newshape)    | Gives a new shape to an array without changing its data. |
| ravel(a)                | Return a contiguous view of the flattened array.                  |
| ndarray.flat            | A 1-D iterator over the array (consumes less memory).                        |
| ndarray.flatten()       | Return a copy of the array collapsed into one dimension. |


In [7]:
## reshape matrix
mat = np.array([[1, 2], [3, 4], [5, 6]]) 

print('old matrix ', mat)
print('old shape is ', mat.shape)

## then reshape it to 6*1 array (column vector)
mat = mat.reshape(6,1)
print('new matrix', mat)
print(' new shape is', mat.shape)

old matrix  [[1 2]
 [3 4]
 [5 6]]
old shape is  (3, 2)
new matrix [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
 new shape is (6, 1)


**REMEMBER** The number of elements is the same in the new matrix and the old matrix, so make sure the new dimension are equivalent to that.

i.e.: the rows_old * columns_old = rows_new * columns_new

This is useful because:

If you know one dimension of the new matrix, but not sure the other dimension, you can let NumPy guess it by placing -1 instead of the new dimension value. **REMEMBER** you can use -1 for only one of the dimensions.

In [ ]:
mat = np.ones((7,4)) ## a 7*4 matrix

## I want to reshape it to 1D array! I know it would look like (x,1) but don't know what x should be
new_matrix = mat.reshape(-1,1) # reshape to 1D array

print(new_matrix.shape) ## it correctly reshaped it!

(28, 1)


Flattening

In [3]:
# Creating a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Using ravel to flatten the array
raveled_arr = np.ravel(arr)
print("Raveled array:")
print(raveled_arr.shape)

Raveled array:
(6,)


### ↪️ Transpose-like operations

| Function                    | Description                                                |
|-----------------------------|------------------------------------------------------------|
| moveaxis(a, source, destination)  | Move axes of an array to new positions.          |
| swapaxes(a, axis1, axis2)  | Interchange two axes of an array (can be used to transpose).                         |
| ndarray.T                  | View of the transposed array (reversed dimensions).                             |
| transpose(a, axes)         | More general than .T (can take new order of dimensions)                   |

In [4]:
# Creating a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Original Array:")
print(arr)

# Transposing the array using .T attribute
transposed_arr = arr.T
print("\nTransposed Array:")
print(transposed_arr)

Original Array:
[[1 2 3]
 [4 5 6]]

Transposed Array:
[[1 4]
 [2 5]
 [3 6]]


### Some Mathematical Operations

Standard Python operations like `*`, `+`, `\`, `==`, etc. are element-wise

In [13]:
## the astrisk * is used for element-wise multiplication
mat1 = np.array([ [1, 2], [3, 4], [5, 6]])  ## of shape 3*2
mat2 = np.array([ [1, 2], [3, 4], [5, 6]])  ## of shape 3*2

mat1_elements_by_mat2_elements = mat1 * mat2 ## they MUST be of the same size
print(mat1_elements_by_mat2_elements)
print('result shape: ', mat1_elements_by_mat2_elements.shape)

[[ 1  4]
 [ 9 16]
 [25 36]]
result shape:  (3, 2)


In [18]:
## Matrix by Matrix Multiplication using np.dot:
mat1 = np.array([ [1, 2], [3, 4], [5, 6]])          ## of shape 3*2
mat2 = np.array([[1, 3, 5], [2, 4, 6]])              ## of shape 2*3

## result matrix is of shape 3*3
mat1_by_mat2 = np.dot(mat1, mat2) ## rememeber, inner dimensions must be the similar

print(mat1_by_mat2)
print('result shape: ', mat1_by_mat2.shape)

## For 1D vectors, falls back to standard dot product
print(np.dot(np.array([1, 2, 3]), np.array([4, 5, 6])))

[[ 5 11 17]
 [11 25 39]
 [17 39 61]]
result shape:  (3, 3)
32


In [20]:
## similar to np.dot, the @ can be used to multiply two matrices arithmatically 
mat1 = np.array([ [1, 2], [3, 4], [5, 6]])      ## of shape 3*2
mat2 = np.array([[1, 3, 5], [2, 4, 6]])         ## of shape 2*3

mat1_by_mat2 = mat1 @ mat2
print(mat1_by_mat2) ## same result
print('result shape: ', mat1_by_mat2.shape)

[[ 5 11 17]
 [11 25 39]
 [17 39 61]]
result shape:  (3, 3)


For more algebraic operations, checks docs for `numpy.linalg` [here](https://numpy.org/doc/stable/reference/routines.linalg.html) and for more mathematical operations in general, check [this](https://numpy.org/doc/stable/reference/routines.math.html). Note that scalar mathematical functions are implemented element-wise.

## 📶 Broadcasting in NumPy

Broadcasting is the MOST important concept in numpy. The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations.



For example:
if we want to add 5 to all values of the array [1, 2, 3] it goes like this: 

In [21]:
arr = np.array([1, 2, 3])
arr_plus_5 = arr + 5       
print(arr_plus_5) 

[6 7 8]


What happened here is that the value 5 is broadcasted to all elements of the array `arr`. Broadcasting means it is **REPEATED** until the shapes are equivalent to perform the `addition` operation.

Another example is if we have the matrix  

`[ [1, 2, 3]
   [1, 2, 3]
   [1, 2, 3]]`
   
and we want to multiply the firs column by 2, the second column by 3, and the third column by 4. 

We can do that using broadcasting of array [2, 3, 4] over the matrix. See:

In [6]:
## create our matrix
mat = np.array([ [1, 2, 3], [1, 2, 3], [1, 2, 3]])

## the multiplication values
multiplication_vals = np.array([2, 3, 4])

## then perform the multiplication using broadcasting:

print(mat * multiplication_vals)

[[ 2  6 12]
 [ 2  6 12]
 [ 2  6 12]]


What happened here is that NumPy found the shape of the first matrix is (3,3) and the second one is (3,) so it repeated the **Smaller** matrix until its shape is like the first one (i.e made it 3 * 3 matrix) then multiplied each element by the corresponding one.

In [ ]:
mat = np.array([ [1, 2, 3], [1, 2, 3], [1, 2, 3]])

**Formal Broadcasting Conditions:**
- If the arrays have a different number of dimensions, the smaller array is padded with ones on its left side to match the number of dimensions of the larger array.

- Array shapes should be compatible: Two dimensions are compatible when they are equal or one of them is 1. If the dimensions of the two arrays are not compatible, NumPy will raise a ValueError.

- Arrays with size 1 along a particular dimension are stretched: If a dimension has size 1 in one of the arrays, it is stretched or repeated along that dimension to match the size of the corresponding dimension in the other array. 

## 🍕 Array Slicing
Indexing arrays in NumPy is easy and useful. We can index sub-arrays, elements and vectors (horizontally and vertically)

In [30]:
mat = np.arange(25).reshape(5,5) ## create a 5*5 array

print(mat)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [10]:
## get the first row
print("first row:", mat[0, :]) ## can also do mat[0]

## get the 2nd column in numpy

print("second column:", mat[:, 1])

first row: [1 2 3]
second column: [2 2 2]


In [34]:
## get the sub array of elements from index (1,1) through the index (3,4)
print(mat[1:4, 1:5]) ## we want rows 1,2 and 3. and columns 1,2,3,4

[[ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]]


## 🎭 Masked Indexing

Another important concept in NumPy is the Masked indexing. We can treat elements of arrays as one object, and index over them using operations.

To check which elements of an array are positive:

In [3]:
arr = np.array([-1, 0, 5, 6, -2, 7, 9, -4]) ## defined array

print(arr > 0)                                ## returns a list of truth (True for +ve and False for non-positive values)

[False False  True  True False  True  True False]


We can use this returned list to index from the array itself!


In [4]:
positive_numbers = arr[ np.array([False, False,  True,  True, False,  True,  True, False]) ]  
positive_numbers = arr[ arr>0 ]  ## the condition the mask above which filters only the elements at index corresponding to True
print(positive_numbers)

[5 6 7 9]


We can use the mask to alter the values of the array itself. 

For example, we want to replace all even values in a list with -1:

In [15]:
array = np.array([1, 2, 3, 4, 5, 6, 7]) ## 

array[ array%2==0 ] = -1 ## the mask returns true for even values, and false for odd values. 
                             ## Then it indexes from the array itsef and assigns -1 to the indices of True values in the mask
print(array)

[ 1 -1  3 -1  5 -1  7]


More operations that you can read about when needed!

### Changing Dimensions
| Function        | Description                                              |
|-----------------|----------------------------------------------------------|
| broadcast       | Produce an object that mimics broadcasting.             |
| expand_dims(a, axis) | Expand the shape of an array.                           |
| squeeze(a, axis)  | Remove axes of length one from a.                        |

### Joining arrays

| Function                 | Description                                                |
|--------------------------|------------------------------------------------------------|
| concatenate((a1, a2, a3,..))            | Join a sequence of arrays along an existing axis.          |
| stack(arrays)            | Join a sequence of arrays along a new axis.                |
| vstack(tup)              | Stack arrays in sequence vertically (row wise).           |
| hstack(tup)              | Stack arrays in sequence horizontally (column wise).       |

### Splitting arrays

| Function                 | Description                                                |
|--------------------------|------------------------------------------------------------|
| split(ary, indices_or_sections) | Split an array into multiple sub-arrays as views into ary. |
| array_split(ary, indices_or_sections) | Split an array into multiple sub-arrays.              |
| dsplit(ary, indices_or_sections) | Split array into multiple sub-arrays along the 3rd axis (depth). |
| hsplit(ary, indices_or_sections) | Split an array into multiple sub-arrays horizontally (column-wise). |
| vsplit(ary, indices_or_sections) | Split an array into multiple sub-arrays vertically (row-wise). |

### Tiling arrays

| Function                 | Description                                                |
|--------------------------|------------------------------------------------------------|
| tile(A, reps)            | Construct an array by repeating A the number of times given by reps. |
| repeat(a, repeats)       | Repeat each element of an array after themselves.          |

### Adding and removing elements

| Function                 | Description                                                |
|--------------------------|------------------------------------------------------------|
| delete(arr, obj)         | Return a new array with sub-arrays along an axis deleted.  |
| insert(arr, obj, values) | Insert values along the given axis before the given indices. |
| append(arr, values)      | Append values to the end of an array.                      |
| resize(a, new_shape)     | Return a new array with the specified shape.              |
| trim_zeros(filt)         | Trim the leading and/or trailing zeros from a 1-D array or sequence. |
| unique(ar)               | Find the unique elements of an array.                      |

### Rearranging elements

| Function                 | Description                                                |
|--------------------------|------------------------------------------------------------|
| flip(m, axis)            | Reverse the order of elements in an array along the given axis. |
| fliplr(m)                | Reverse the order of elements along axis 1 (left/right).   |
| flipud(m)                | Reverse the order of elements along axis 0 (up/down).      |
| reshape(a, newshape)     | Gives a new shape to an array without changing its data.   |
| roll(a, shift, axis)     | Roll array elements along a given axis.                    |
| rot90(m, k, axes)        | Rotate an array by 90 degrees in the plane specified by axes. |

## 🧮 Aggregation

NumPy provides a lot of common aggregation functions for arrays.

In [37]:
 # sum, mean, var, std and A LOT more!
arr = np.arange(5) ## similar to np.array([0, 1, 2, 3, 4])
print(arr.mean())    

# If axis is specified, the function does not over the whole array

arr = np.arange(10).reshape(5,2) ## creates a 5*2 array of values from 0-9
print(arr.mean(axis=0))  ## axis = 0 means it creates the mean over the columns (0-> colums, 1->rows)

print(arr.mean(axis=1)) ## axis = 1 for means of rows

2.0
[4. 5.]
[0.5 2.5 4.5 6.5 8.5]


For more statistical operations, check the docs [here](https://numpy.org/doc/stable/reference/routines.statistics.html)

## 🎲 Random


The `np.random` has a bunch of useful functions for random behavior
- We have `randint()` for random integers, `rand()` for random floats in `[0,1)` and `randn()` for random floats following a standard normal distribution.
    - They return a scalar if no shape is specified.

In [8]:
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Generate an array of 5 random integers between 50 and 150
random_int_array = np.random.randint(low=50, high=150, size=(3,2))
print("Random Integer Array:", random_int_array, sep="\n", end="\n\n")

# Generate a 3x3 array of random floats between 0 and 1 (how to do better?)
random_float_array = np.random.rand(3, 3) 
print("Random Float Array:", random_float_array, sep="\n", end="\n\n")

# Generate a 2x2 array of random numbers from a standard normal distribution (how to do better?)
random_normal_array = np.random.randn(2, 2)
print("Random Numbers from Normal Distribution:", random_normal_array, sep="\n", end="\n\n")

Random Integer Array:
[[101 142]
 [ 64 121]
 [110  70]]

Random Float Array:
[[0.15601864 0.15599452 0.05808361]
 [0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264]]

Random Numbers from Normal Distribution:
[[-0.58087813 -0.52516981]
 [-0.57138017 -0.92408284]]



- We have `choice()` to choose a random sample from a list and `shuffle` to shuffle a list

In [ ]:
# Shuffle elements of a list
my_list = [1, 2, 3, 4, 5]
np.random.shuffle(my_list)
print("Shuffled List:", my_list)

# Choose random elements from a list
my_list = ['a', 'b', 'c', 'd', 'e']
random_choice = np.random.choice(my_list, size=3, replace=False)
print("Randomly Chosen Elements from List:", random_choice)

## 📚 Linear Algebra

The `np.linalg` module has a handful of useful Algebraic functions

In [10]:
import numpy as np

# Define a square matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Compute the determinant of A
determinant_A = np.linalg.det(A)
print("Determinant of Matrix A:", determinant_A,  sep="\n", end="\n\n")

# Compute the eigenvalues and eigenvectors of A
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues of Matrix A:", eigenvalues,  sep="\n")
print("Eigenvectors of Matrix A:", eigenvectors,  sep="\n", end="\n\n")

# Compute the inverse of A
A_inv = np.linalg.inv(A)
print("Inverse of Matrix A:", A_inv,  sep="\n")

Determinant of Matrix A:
-9.51619735392994e-16

Eigenvalues of Matrix A:
[ 1.61168440e+01 -1.11684397e+00 -8.58274334e-16]
Eigenvectors of Matrix A:
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]

Inverse of Matrix A:
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
