## EinSum

We can describe matrix multiplication of two matrices $A_{m×n}$ and $B_{n×k}$ as follows in index form as follow $C_{m×k}$:

$$C_{ik}=\sum_{j=1}^{n}{A_{ij}×B_{jk}}$$

Einstein would write sums in an equivalent simpler form:

$$c_{ik}=a_{ij}b_{jk}$$

Many other vector operations can be written in an index form wouldn't it be nice if we have a function that we provide the einstein notation and have it itself implement the compuation in parallel! This is what `np.einsum` is for
```python
C = np.einsum('ij,jk->ik', A, B)
```

#### Mathematical way to read this:
- Write it index for similar to the first equation while summing over any index repeated across inputs only.
<br><br>

#### Programming way to read this:
1. Dimensions of A and B are `2x2` and the result C will be `2x2` it will be of shape `(A.shape[0], B.shape[1])`
2. A loop will be made for each free index and in the body of the loop a sum will be made over the free indices
```python
# From (1)
C = np.zeros((A.shape[0], B.shape[1]))  
# From (2)
for i in range(A.shape[0]):  
    for k in range(B.shape[1]):  
        C[i, k] = sum([A[i, j] * B[j, k] for j in range A.shape[1]])
```

#### Why EinSum is Awesome


- **Generic**: Can implement any vector operation by writing it index form! (more below)
- **Fast**: Gets computed in parallel! (will use it in the lab to speed up KDE!)
- **Novel**: Can invent new operations and used them for efficient implementations (e.g., deep learning)

### 🧪 Examples

In [18]:
import numpy as np

#### Dot Product

In [19]:
# Create two vectors
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

dot_product = np.einsum('i,i->', A, B)          #aibi => Σaibi
print(dot_product)  

32


#### Outer Product

In [8]:
# Create two vectors
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Calculate outer product using einsum
outer_product = np.einsum('i,j->ij', a, b)      #for i in range A.shape[0] for j in range B.shape[0]: cij=ai*bj
print(outer_product)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


#### Element-wise Multiplication

In [9]:
# Create two arrays
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# Calculate element-wise multiplication using einsum
element_wise_product = np.einsum('ij,ij->ij', A, B)     #for i in range A.shape[0] for j in range B.shape[0]: cij=ai*bj
print(element_wise_product)

[[ 5 12]
 [21 32]]


#### Matrix Multiplication

In [10]:
import numpy as np

# Create two matrices
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# Calculate matrix multiplication using einsum
matrix_product = np.einsum('ij,jk->ik', A, B)
print(matrix_product)

[[19 22]
 [43 50]]


#### Batch Matrix Multiplication

In [15]:
# Create batch of matrices
batch_A = np.random.rand(3, 2, 2)  #  3x2x2 
batch_B = np.random.rand(3, 2, 2)  #  3x2x2

# Calculate batch matrix multiplication using einsum
batch_matrix_product = np.einsum('aij,ajk->aik', batch_A, batch_B)     


assert np.allclose(batch_matrix_product, np.array([batch_A[i] @ batch_B[i] for i in range(3)]))

#### Matrix Sum

In [20]:
A = np.array([[1, 2],
              [3, 4]])

# Calculate the sum of all elements using einsum
matrix_sum = np.einsum('ij->', A)       # Σi,j aij
print(matrix_sum)  # Output: 10

10


### Trace

In [21]:
A = np.array([[1, 2],
              [3, 4]])

# Calculate trace using einsum
trace_A = np.einsum('ii->', A)  # Σ_i a_ii
print(trace_A)  

5
