# 🐼 Pandas Package 

Name comes from `panel data`

Modified from [this source](https://www.reddit.com/r/Palestine/comments/1aqhfat/theres_an_ongoing_food_crisis_in_palestine_yet/)

In [1]:
import pandas as pd

# Loading in Data

The first step in any ML problem is identifying what format your data is in, and then loading it into whatever framework you're using. 

We will use the NCAA basketball games from 1985 to 2016 dataset. The `read_csv` function returns a **dataframe** variable. The dataframe is defined as "a two-dimensional size-mutable, potentially heterogeneous tabular data structure with labeled axes (rows and columns)".

Just think of it as a table for now. 

In [81]:
df = pd.read_csv('./data/RegularSeasonCompactResults.csv')
df

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0         1985      20   1228      81   1328      64    N      0
1         1985      25   1106      77   1354      70    H      0
2         1985      25   1112      63   1223      56    H      0
3         1985      25   1165      70   1432      54    H      0
4         1985      25   1192      86   1447      74    H      0
...        ...     ...    ...     ...    ...     ...  ...    ...
145284    2016     132   1114      70   1419      50    N      0
145285    2016     132   1163      72   1272      58    N      0
145286    2016     132   1246      82   1401      77    N      1
145287    2016     132   1277      66   1345      62    N      0
145288    2016     132   1386      87   1433      74    N      0

[145289 rows x 8 columns]

# The Basics

Now that we have our dataframe in our variable df, let's look at what it contains. We can use the function **head()** to see the first couple rows of the dataframe (or the function **tail()** to see the last few rows).

In [82]:
df.head()

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228      81   1328      64    N      0
1    1985      25   1106      77   1354      70    H      0
2    1985      25   1112      63   1223      56    H      0
3    1985      25   1165      70   1432      54    H      0
4    1985      25   1192      86   1447      74    H      0

In [60]:
df.tail()

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
145284    2016     132   1114      70   1419      50    N      0
145285    2016     132   1163      72   1272      58    N      0
145286    2016     132   1246      82   1401      77    N      1
145287    2016     132   1277      66   1345      62    N      0
145288    2016     132   1386      87   1433      74    N      0

Access a column as a series (like a list but has a name)

In [93]:
df['Wscore']

0         81
1         77
2         63
3         70
4         86
          ..
145284    70
145285    72
145286    82
145287    66
145288    87
Name: Wscore, Length: 145289, dtype: int64

Access a column as a dataframe

In [95]:
df[['Wscore']]

Wscore
0           81
1           77
2           63
3           70
4           86
...        ...
145284      70
145285      72
145286      82
145287      66
145288      87

[145289 rows x 1 columns]

#### Difference between series and dataframe

- Series has a single column
- Can index series directly with a constant from the index but not dataframes
    - They are easy to convert to lists

In [97]:
# df[['Wscore']][1]
df['Wscore']

0         81
1         77
2         63
3         70
4         86
          ..
145284    70
145285    72
145286    82
145287    66
145288    87
Name: Wscore, Length: 145289, dtype: int64

We can see the dimensions of the dataframe using the the **shape** attribute

In [98]:
df.shape

(145289, 8)

We can also extract all the column names as a list, by using the **columns** attribute and can extract the rows with the **index** attribute

In [100]:
df.columns.tolist()

['Season', 'Daynum', 'Wteam', 'Wscore', 'Lteam', 'Lscore', 'Wloc', 'Numot']

In order to get a better idea of the type of data that we are dealing with, we can call the **describe()** function to see statistics like mean, min, etc about each column of the dataset. 

In [103]:
df.describe()

Wteam         Wscore          Lteam         Lscore  \
count  145289.000000  145289.000000  145289.000000  145289.000000   
mean     1286.720646      76.600321    1282.864064      64.497009   
std       104.570275      12.173033     104.829234      11.380625   
min      1101.000000      34.000000    1101.000000      20.000000   
25%      1198.000000      68.000000    1191.000000      57.000000   
50%      1284.000000      76.000000    1280.000000      64.000000   
75%      1379.000000      84.000000    1375.000000      72.000000   
max      1464.000000     186.000000    1464.000000     150.000000   

               Numot  
count  145289.000000  
mean        0.044387  
std         0.247819  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         0.000000  
max         6.000000

Okay, so now let's looking at information that we want to extract from the dataframe. Let's say I wanted to know the max value of a certain column. The function **max()** will show you the maximum values of all columns

In [105]:
df.max()

Season    2016
Daynum     132
Wteam     1464
Wscore     186
Lteam     1464
Lscore     150
Wloc         N
Numot        6
dtype: object

Columns can be indexed similar to dictionaries:

In [49]:
df['Wscore'].max()

186

But what if that's not enough? Let's say we want to actually see the game(row) where this max score happened. We can call the **argmax()** function to identify the row index

In [107]:
df['Wscore'][24970]

186

One of the most useful functions that you can call on certain columns in a dataframe is the **value_counts()** function. It is basically a histogram for the column;s values.

In [109]:
df['Season'].value_counts()

Season
2016    5369
2014    5362
2015    5354
2013    5320
2010    5263
2012    5253
2009    5249
2011    5246
2008    5163
2007    5043
2006    4757
2005    4675
2003    4616
2004    4571
2002    4555
2000    4519
2001    4467
1999    4222
1998    4167
1997    4155
1992    4127
1991    4123
1996    4122
1995    4077
1994    4060
1990    4045
1989    4037
1993    3982
1988    3955
1987    3915
1986    3783
1985    3737
Name: count, dtype: int64

# Acessing Values

You can access rows by using slicing operations while indexing the dataframe directly. 

In [116]:
df[0:1]

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228      81   1328      64    N      0

With indexing directly:
- Can select a subset of rows
- Can select a subset of column
- Cannot do both together!

But generally use `loc` for this for better generality.

In [121]:
df.loc[0:3]

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228      81   1328      64    N      0
1    1985      25   1106      77   1354      70    H      0
2    1985      25   1112      63   1223      56    H      0
3    1985      25   1165      70   1432      54    H      0

In [125]:
df.loc[[1]]

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
1    1985      25   1106      77   1354      70    H      0

In [16]:
df.loc[ [df['Wscore'].argmax()] ]      

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
24970    1991      68   1258     186   1109     140    H      0

When not using a range or a list to index with:

In [133]:
df.loc[6, 'Wscore']            # to return a row as a series

64

# Sorting

Let's say that we want to sort the dataframe in increasing order for the scores of the losing team

In [36]:
df.sort_values('Lscore').head()

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
100027    2008      66   1203      49   1387      20    H      0
49310     1997      66   1157      61   1204      21    H      0
89021     2006      44   1284      41   1343      21    A      0
85042     2005      66   1131      73   1216      22    H      0
103660    2009      26   1326      59   1359      22    H      0

# Filtering Rows Conditionally

Now, let's say we want to find all of the rows that satisy a particular condition. For example, I want to find all of the games where the winning team scored more than 150 points. The idea behind this command is you want to access the column `Wscore` of the dataframe df `(df['Wscore'])`, find which entries are above 150 `(df['Wscore'] > 150)`, and then returns only those specific rows in a dataframe format `(df[df['Wscore'] > 150])`.

In [134]:
df[ df['Wscore'] > 150 ]

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
5269     1986      75   1258     151   1109     107    H      0
12046    1988      40   1328     152   1147      84    H      0
12355    1988      52   1328     151   1173      99    N      0
16040    1989      40   1328     152   1331     122    H      0
16853    1989      68   1258     162   1109     144    A      0
17867    1989      92   1258     181   1109     150    H      0
19653    1990      30   1328     173   1109     101    H      0
19971    1990      38   1258     152   1109     137    A      0
20022    1990      40   1116     166   1109     101    H      0
22145    1990      97   1258     157   1362     115    H      0
23582    1991      26   1318     152   1258     123    N      0
24341    1991      47   1328     172   1258     112    H      0
24970    1991      68   1258     186   1109     140    H      0
25656    1991      84   1106     151   1212      97    H      0
28687    1992      54   1261     159   1319      86    H      0
35023    1993     112   1380     155   1341      91    A      0
40060    1995      32   1375     156   1341     114    H      0
52600    1998      33   1395     153   1410      87    H      0

This also works if you have multiple conditions. Let's say we want to find out when the winning team scores more than 150 points and when the losing team scores below 100. 

In [39]:
df[(df['Wscore'] > 150) & (df['Lscore'] < 100)]

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
12046    1988      40   1328     152   1147      84    H      0
12355    1988      52   1328     151   1173      99    N      0
25656    1991      84   1106     151   1212      97    H      0
28687    1992      54   1261     159   1319      86    H      0
35023    1993     112   1380     155   1341      91    A      0
52600    1998      33   1395     153   1410      87    H      0

Similar to the argmax we performed earlier above

In [3]:
import numpy as np

def broadcast_operation(arr1, arr2):
    # Perform broadcasting operation
    result = arr1 + arr2
    return result

arr1 = np.array([[[1, 2],
                  [3, 4]],
                 
                 [[5, 6],
                  [7, 8]]])

arr2 = np.array([[10, 20]])

result = broadcast_operation(arr1, arr2)

[[[11 22]
  [13 24]]

 [[15 26]
  [17 28]]]


In [135]:
df[df['Wscore'] == df['Wscore'].max()]

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
24970    1991      68   1258     186   1109     140    H      0

# Dataframe Iteration

In order to iterate through dataframes, we can use the **iterrows()** function. Below is an example of what the first two rows look like. Each row in iterrows is a Series object

In [136]:
for index, row in df.iterrows():
    print(row)
    if index == 1:
        break

Season    1985
Daynum      20
Wteam     1228
Wscore      81
Lteam     1328
Lscore      64
Wloc         N
Numot        0
Name: 0, dtype: object
Season    1985
Daynum      25
Wteam     1106
Wscore      77
Lteam     1354
Lscore      70
Wloc         H
Numot        0
Name: 1, dtype: object


# Data Cleaning

One of the big jobs of doing well in data science is that of data cleaning. A lot of times, the CSV file you're given, you'll have a lot of missing values in the dataset, which you have to identify. 

The following `isnull` function will figure out if there are any missing values in the dataframe, and will then sum up the total for each column. In this case, we have a pretty clean dataset.

In [138]:
df.isnull().sum()

Season    0
Daynum    0
Wteam     0
Wscore    0
Lteam     0
Lscore    0
Wloc      0
Numot     0
dtype: int64

If you do end up having missing values in your datasets, be sure to get familiar with these two functions. 
* **dropna()** - This function allows you to drop all(or some) of the rows that have missing values. 
* **fillna()** - This function allows you replace the rows that have missing values with the value that you pass in.

Convert Pandas to Numpy Array

In [139]:
import pandas as pd

df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
df

A  B
0  1  4
1  2  5
2  3  6

In [140]:

arr = df.values
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[[1 4]
 [2 5]
 [3 6]]
