#### Define a 2D Array

In [29]:
import numpy as np

matrix = np.array([ [1, 2, 6],
                    [7, 5, 3],
                    [4, 8, 9]])

#### Along Axis 0,1

In [42]:
sum_ = np.argmax(matrix, axis=1)     # mean(col1, col2, col3)
sum_

array([2, 0, 2])

#### Higher Dimensions

<img src="https://i.imgur.com/uVpQP3o.jpeg" width=300>

In [21]:
np.random.seed(42)
array_4d = np.random.randint(0, 5, size=(2, 3, 2, 4))
array_4d

array([[[[3, 4, 2, 4],
         [4, 1, 2, 2]],

        [[2, 4, 3, 2],
         [4, 1, 3, 1]],

        [[3, 4, 0, 3],
         [1, 4, 3, 0]]],


       [[[0, 2, 2, 1],
         [3, 3, 2, 3]],

        [[3, 0, 2, 4],
         [2, 4, 0, 1]],

        [[3, 0, 3, 1],
         [1, 0, 1, 4]]]])

#### Along Axis 0

In [46]:
sum_axis_0 = np.sum(array_4d, axis=3)
sum_axis_0

array([[[13,  9],
        [11,  9],
        [10,  8]],

       [[ 5, 11],
        [ 9,  7],
        [ 7,  6]]])

Interesting link with [visual numpy](https://jalammar.github.io/visual-numpy/)